#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jeedom"
name = "Jeedom"
description.en = "Home automation application"
description.fr = "Application de domotique"

version = "4.4.19~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0-or-later"
website = "https://www.jeedom.com"
admindoc = "https://doc.jeedom.com"
code = "https://github.com/jeedom/core"
cpe = "cpe:2.3:a:jeedom:jeedom"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = true

sso = true

disk = "200M"
ram.build = "200M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jeedom"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.sudo]
    ask.en = "Do you agree giving sudo rights to the Jeedom user? This is required for most Jeedom features to work. However, attackers could use vulnerabilities in Jeedom to take control of your server."
    ask.fr = "Acceptez-vous de donner les droits sudo à l'utilisateur Jeedom ? Ces droits sont nécessaires au bon fonctionnement de Jeedom. Toutefois, des attaquants pourraient exploiter des failles de Jeedom pour prendre le controle de votre serveur."
    type = "boolean"
    default = true

[resources]
    [resources.sources.main]
    url = "https://github.com/jeedom/core/archive/refs/tags/4.4.19.tar.gz"
    sha256 = "129ab1d9359c694e5964a7a01a506ce5be6044599112b72d7b316cae0dee1c43"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "ntp",
        "unzip",
        "curl",
        "cron",
        "locate",
        "tar",
        "telnet",
        "wget",
        "logrotate",
        "dos2unix",
        "ntpdate",
        "htop",
        "iotop",
        "iftop",
        "smbclient",
        "python3",
        "python3-pip",
        "libexpat1",
        "xvfb",
        "cutycapt",
        "xauth",
        "at",
        "espeak",
        "net-tools",
        "nmap",
        "ffmpeg",
        "usbutils",
        "gettext",
        "libcurl3-gnutls",
        "librsync-dev",
        "iputils-ping",
        "php8.2-json",
        "php8.2-mysql",
        "php8.2-curl",
        "php8.2-gd",
        "php8.2-imap",
        "php8.2-xml",
        "php8.2-opcache",
        "php8.2-soap",
        "php8.2-xmlrpc",
        "php8.2-dev",
        "php8.2-zip",
        "php8.2-ssh2",
        "php8.2-mbstring",
        "php8.2-ldap",
        "php8.2-yaml",
        "php8.2-snmp",
        "mariadb-server",
    ]

    [resources.apt.extras.nonfree]
    repo = "deb http://deb.debian.org/debian bullseye contrib non-free"
    key = "https://ftp-master.debian.org/keys/release-11.asc"
    packages = [
        "libsox-fmt-mp3",
        "sox",
        "libttspico-utils",
        "espeak",
        "mbrola",
        "brltty",
        "net-tools",
        "nmap",
    ]

    [resources.database]
    type = "mysql"
