#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.7c7a55f99f8a593078fc37d2200bd6ca86766233.name = "3.3.45~ynh1"
    # test_upgrade_from.4067b16fa1ef2c15247089852a5aca3249bf466a.name = "3.3.45~ynh2"
    # test_upgrade_from.bbf6b7145f37b4e918d80d3293628970fc0acb51.name = "4.1.19~ynh1"
    # test_upgrade_from.9bf6bf9b59e9b2c9f344c7ff70e506a80b6b13f0.name = "4.1.19~ynh5"
    test_upgrade_from.9a0dd1f0806869f6f1fb49ece3cfd46776128090.name = "Upgrade from 4.4.19~ynh1"
