#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=1G

#=================================================
# CONFIGURING RIGHTS
#=================================================
ynh_script_progression "Configuring permissions..."

_jeedom_set_permission

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

# FIXME: is it used?? It's not even reboot persistent…
# Create tmp required by Jeedom
mkdir -p /tmp/jeedom
chmod 750 /tmp/jeedom
chown "$app:www-data" -R /tmp/jeedom

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="common.config.php" --destination="$install_dir/core/config/common.config.php"

#=================================================
# INSTALL JEEDOM
#=================================================
ynh_script_progression "Installing $app..."

# Install Jeedom
"php$php_version" "$install_dir/install/install.php" mode=force

# Configure LDAP and the Admin User and access settings
ynh_config_add --template="config.sql" --destination="$install_dir/config.sql"
ynh_mysql_db_shell " < "$install_dir/config.sql""
ynh_safe_rm "$install_dir/config.sql"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cronjeedom" --destination="/etc/cron.d/${app}"
ynh_config_add --template="cronjeedom_watchdog" --destination="/etc/cron.d/${app}_watchdog"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
