#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_upload_max_filesize --value=50M
ynh_app_setting_set --key=php_post_max_size --value=50M

#=================================================
# CONFIGURING RIGHTS
#=================================================
ynh_script_progression "Configuring permissions..."

_jeedom_set_permission

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

# Create tmp required by Jeedom
mkdir -p "/tmp/jeedom/cache/"
chmod -R 775 "/tmp/jeedom/"
chown -R "$app:www-data" "/tmp/jeedom/"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="common.config.php" --destination="$install_dir/core/config/common.config.php"

chmod 400 "$install_dir/core/config/common.config.php"
chown "$app:$app" "$install_dir/core/config/common.config.php"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Cron
ynh_config_add --template="cronjeedom" --destination="/etc/cron.d/${app}"
ynh_config_add --template="cronjeedom_watchdog" --destination="/etc/cron.d/${app}_watchdog"

#=================================================
# INSTALL JEEDOM
#=================================================
ynh_script_progression "Installing $app..."

# Install Jeedom
ynh_composer_exec install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader
"php$php_version" "$install_dir/install/install.php" mode=force

# Configure LDAP and the Admin User and access settings
ynh_config_add --template="config.sql" --destination="$install_dir/config.sql"
ynh_mysql_db_shell < "$install_dir/config.sql"
ynh_safe_rm "$install_dir/config.sql"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
