#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# Remove cron files
ynh_safe_rm "/etc/cron.d/${app}"
ynh_safe_rm "/etc/cron.d/${app}_watchdog"

ynh_safe_rm "/tmp/jeedom/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
