#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_nginx

ynh_config_remove_phpfpm

# Remove other various files specific to the app... such as:

ynh_safe_rm "/etc/cron.d/${app}"
ynh_safe_rm "/etc/cron.d/${app}_watchdog"

ynh_safe_rm "/tmp/jeedom/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
